<?php

/**
 * This is the model base class for the table "vnc.bo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Bo".
 *
 * Columns in table "vnc.bo" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $ID
 * @property string $Viet
 * @property string $LaTin
 * @property integer $Nhom
 *
 */
abstract class BaseBo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'bo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Bo|Bos', $n);
	}

	public static function representingColumn() {
		return 'Viet';
	}

	public function rules() {
		return array(
			array('ID, Nhom', 'numerical', 'integerOnly'=>true),
			array('Viet, LaTin', 'length', 'max'=>50),
			array('ID, Viet, LaTin, Nhom', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ID, Viet, LaTin, Nhom', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
				'ID' => array(self::HAS_MANY, 'Creatures', 'Bo'),
				'ID' => array(self::HAS_MANY, 'Ho', 'Bo'),
				'rNhom'=>array(self::BELONGS_TO, 'Nhom', 'Nhom'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID' => Yii::t('app', 'ID'),
			'Viet' => Yii::t('app', 'Tên Việt'),
			'LaTin' => Yii::t('app', 'Tên La Tin'),
			'Nhom' => Yii::t('app', 'Nhóm'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID', $this->ID);
		$criteria->compare('Viet', $this->Viet, true);
		$criteria->compare('LaTin', $this->LaTin, true);
		$criteria->compare('Nhom', $this->Nhom);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}