<?php

/**
 * This is the model base class for the table "users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Users".
 *
 * Columns in table "users" available as properties of the model,
 * followed by relations of table "users" available as properties of the model.
 *
 * @property integer $user_id
 * @property string $facebook_id
 * @property string $username
 * @property string $user_dob
 * @property string $user_address
 * @property string $user_email
 * @property integer $last_time_login
 * @property string $user_avatar
 * @property string $name
 *
 * @property Posts[] $posts
 * @property Reports[] $reports
 */
abstract class BaseUsers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'users';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Users|Users', $n);
	}

	public static function representingColumn() {
		return 'facebook_id';
	}

	public function rules() {
		return array(
			array('facebook_id, name', 'required'),
			array('last_time_login', 'numerical', 'integerOnly'=>true),
			array('facebook_id, username, user_address, user_email, user_avatar, name', 'length', 'max'=>255),
			array('user_dob', 'length', 'max'=>20),
			array('username, user_dob, user_address, user_email, last_time_login, user_avatar', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, facebook_id, username, user_dob, user_address, user_email, last_time_login, user_avatar, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'posts' => array(self::HAS_MANY, 'Posts', 'user_id'),
			'reports' => array(self::HAS_MANY, 'Reports', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => Yii::t('app', 'User'),
			'facebook_id' => Yii::t('app', 'Facebook'),
			'username' => Yii::t('app', 'Username'),
			'user_dob' => Yii::t('app', 'User Dob'),
			'user_address' => Yii::t('app', 'User Address'),
			'user_email' => Yii::t('app', 'User Email'),
			'last_time_login' => Yii::t('app', 'Last Time Login'),
			'user_avatar' => Yii::t('app', 'User Avatar'),
			'name' => Yii::t('app', 'Name'),
			'posts' => null,
			'reports' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('facebook_id', $this->facebook_id, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('user_dob', $this->user_dob, true);
		$criteria->compare('user_address', $this->user_address, true);
		$criteria->compare('user_email', $this->user_email, true);
		$criteria->compare('last_time_login', $this->last_time_login);
		$criteria->compare('user_avatar', $this->user_avatar, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}