<?php

/**
 * This is the model base class for the table "national_parks".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NationalParks".
 *
 * Columns in table "national_parks" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $park_name
 * @property string $park_description
 * @property double $longitude
 * @property double $latitude
 *
 */
abstract class BaseNationalParks extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'national_parks';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NationalParks|NationalParks', $n);
	}

	public static function representingColumn() {
		return 'park_name';
	}

	public function rules() {
		return array(
			array('park_name, park_description, longitude, latitude', 'required'),
			array('longitude, latitude', 'numerical'),
			array('park_name', 'length', 'max'=>255),
			array('id, park_name, park_description, longitude, latitude', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => 'ID',
			'park_name' => 'Tên Vườn Quốc Gia',
			'park_description' => 'Mô tả Vườn Quốc Gia',
			'longitude' => 'Kinh độ',
			'latitude' => 'Vĩ độ',
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('park_name', $this->park_name, true);
		$criteria->compare('park_description', $this->park_description, true);
		$criteria->compare('longitude', $this->longitude);
		$criteria->compare('latitude', $this->latitude);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}