<?php

/**
 * This is the model base class for the table "creatures_provinces_relation".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CreaturesProvincesRelation".
 *
 * Columns in table "creatures_provinces_relation" available as properties of the model,
 * followed by relations of table "creatures_provinces_relation" available as properties of the model.
 *
 * @property integer $id
 * @property integer $creature_id
 * @property integer $province_id
 *
 * @property Coordinations $province
 */
abstract class BaseCreaturesProvincesRelation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'creatures_provinces_relation';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CreaturesProvincesRelation|CreaturesProvincesRelations', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('creature_id, province_id', 'required',
						'message'=>'Hãy vui lòng nhập giá trị cho {attribute}.'),
			array('creature_id, province_id', 'numerical', 'integerOnly'=>true),
			array('id, creature_id, province_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'creature_id' => Yii::t('app', 'Creature'),
			'province_id' => null,
			'province' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('creature_id', $this->creature_id);
		$criteria->compare('province_id', $this->province_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}