<?php

/**
 * This is the model base class for the table "thread_images".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Thread_images".
 *
 * Columns in table "thread_images" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $thread_image_id
 * @property string $image_link
 * @property integer $thread_id
 *
 */
abstract class BaseThread_images extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'thread_images';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Thread_images|Thread_images', $n);
	}

	public static function representingColumn() {
		return 'image_link';
	}

	public function rules() {
		return array(
			array('image_link, thread_id', 'required'),
			array('thread_id', 'numerical', 'integerOnly'=>true),
			array('image_link', 'length', 'max'=>255),
			array('thread_image_id, image_link, thread_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'thread_image_id' => Yii::t('app', 'Thread Image'),
			'image_link' => Yii::t('app', 'Image Link'),
			'thread_id' => Yii::t('app', 'Thread'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('thread_image_id', $this->thread_image_id);
		$criteria->compare('image_link', $this->image_link, true);
		$criteria->compare('thread_id', $this->thread_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}