<?php

/**
 * This is the model base class for the table "loai".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Loai".
 *
 * Columns in table "loai" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $ID
 * @property string $Loai
 *
 */
abstract class BaseLoai extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'loai';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Loai|Loais', $n);
	}

	public static function representingColumn() {
		return 'Loai';
	}

	public function rules() {
		return array(
			array('Loai', 'length', 'max'=>50),
			array('Loai', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ID, Loai', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
				'ID' => array(self::HAS_MANY, 'Creatures', 'Loai'),
				'ID' => array(self::HAS_MANY, 'Nhom', 'Loai'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID' => Yii::t('app', 'ID'),
			'Loai' => Yii::t('app', 'Loai'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID', $this->ID);
		$criteria->compare('Loai', $this->Loai, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}