<?php

/**
 * This is the model base class for the table "notifications".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Notifications".
 *
 * Columns in table "notifications" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $notification_id
 * @property integer $thread_id
 * @property integer $user_id
 * @property integer $viewed_status
 *
 */
abstract class BaseNotifications extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'notifications';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Notifications|Notifications', $n);
	}

	public static function representingColumn() {
		return 'notification_id';
	}

	public function rules() {
		return array(
			array('thread_id, user_id', 'required'),
			array('thread_id, user_id, viewed_status', 'numerical', 'integerOnly'=>true),
			array('viewed_status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('notification_id, thread_id, user_id, viewed_status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'notification_id' => Yii::t('app', 'Notification'),
			'thread_id' => Yii::t('app', 'Thread'),
			'user_id' => Yii::t('app', 'User'),
			'viewed_status' => Yii::t('app', 'Viewed Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('notification_id', $this->notification_id);
		$criteria->compare('thread_id', $this->thread_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('viewed_status', $this->viewed_status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}